name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  buildAndPack:
    # Use MacOS because on ubunut-latest, Fable hangs for some reason.
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Restore dependencies
      run: |
        dotnet tool restore
        dotnet restore
    - name: install npm packages
      run: npm install
    - name: Build
      run: dotnet fable --outDir "extension"
    - name: Pack
      run: npm run pack
    - name: Upload extension as artifact
      uses: actions/upload-artifact@v4
      with:
        name: extension
        path: extension/web-ext-artifacts/*.zip
