name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  buildAndPack:
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macOS-latest
        fableVersion:
        - "4.27.0"
        - "5.0.0-alpha.15"
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Restore dependencies
      run: |
        dotnet tool install fable --version ${{ matrix.fableVersion }}
        dotnet tool restore
        dotnet restore
    - name: install npm packages
      run: npm install
    - name: Build
      run: dotnet fable --outDir "extension" --verbose
    - name: Pack
      run: npm run pack
    - name: Upload extension as artifact
      uses: actions/upload-artifact@v4
      with:
        name: extension
        path: extension/web-ext-artifacts/*.zip
        # Overwrite the artifact instead of failing.
        # This is needed because different combinations of (OS, Fable version) will try to upload the same artifact.
        overwrite: true
